class SuraModel {
  String arName, enName, ayaNumber;
  SuraModel({
    required this.arName,
    required this.enName,
    required this.ayaNumber,
  });

  static List<SuraModel> surasList = [
    SuraModel(arName: "الفاتحه", enName: "Al-Fatiha", ayaNumber: '7'),
    SuraModel(arName: "البقرة", enName: "Al-Baqarah", ayaNumber: '286'),
    SuraModel(arName: "آل عمران", enName: "Aal-E-Imran", ayaNumber: '200'),
    SuraModel(arName: "النساء", enName: "An-Nisa'", ayaNumber: '176'),
    SuraModel(arName: "المائدة", enName: "Al-Ma'idah", ayaNumber: '120'),
    SuraModel(arName: "الأنعام", enName: "Al-An'am", ayaNumber: '165'),
    SuraModel(arName: "الأعراف", enName: "Al-A'raf", ayaNumber: '206'),
    SuraModel(arName: "الأنفال", enName: "Al-Anfal", ayaNumber: '75'),
    SuraModel(arName: "التوبة", enName: "At-Tawbah", ayaNumber: '129'),
    SuraModel(arName: "يونس", enName: "Yunus", ayaNumber: '109'),
    SuraModel(arName: "هود", enName: "Hud", ayaNumber: '123'),
    SuraModel(arName: "يوسف", enName: "Yusuf", ayaNumber: '111'),
    SuraModel(arName: "الرعد", enName: "Ar-Ra'd", ayaNumber: '43'),
    SuraModel(arName: "إبراهيم", enName: "Ibrahim", ayaNumber: '52'),
    SuraModel(arName: "الحجر", enName: "Al-Hijr", ayaNumber: '99'),
    SuraModel(arName: "النحل", enName: "An-Nahl", ayaNumber: '128'),
    SuraModel(arName: "الإسراء", enName: "Al-Isra", ayaNumber: '111'),
    SuraModel(arName: "الكهف", enName: "Al-Kahf", ayaNumber: '110'),
    SuraModel(arName: "مريم", enName: "Maryam", ayaNumber: '98'),
    SuraModel(arName: "طه", enName: "Ta-Ha", ayaNumber: '135'),
    SuraModel(arName: "الأنبياء", enName: "Al-Anbiya", ayaNumber: '112'),
    SuraModel(arName: "الحج", enName: "Al-Hajj", ayaNumber: '78'),
    SuraModel(arName: "المؤمنون", enName: "Al-Mu'minun", ayaNumber: '118'),
    SuraModel(arName: "النّور", enName: "An-Nur", ayaNumber: '64'),
    SuraModel(arName: "الفرقان", enName: "Al-Furqan", ayaNumber: '77'),
    SuraModel(arName: "الشعراء", enName: "Ash-Shu'ara", ayaNumber: '227'),
    SuraModel(arName: "النّمل", enName: "An-Naml", ayaNumber: '93'),
    SuraModel(arName: "القصص", enName: "Al-Qasas", ayaNumber: '88'),
    SuraModel(arName: "العنكبوت", enName: "Al-Ankabut", ayaNumber: '69'),
    SuraModel(arName: "الرّوم", enName: "Ar-Rum", ayaNumber: '60'),
    SuraModel(arName: "لقمان", enName: "Luqman", ayaNumber: '34'),
    SuraModel(arName: "السجدة", enName: "As-Sajda", ayaNumber: '30'),
    SuraModel(arName: "الأحزاب", enName: "Al-Ahzab", ayaNumber: '73'),
    SuraModel(arName: "سبأ", enName: "Saba", ayaNumber: '54'),
    SuraModel(arName: "فاطر", enName: "Fatir", ayaNumber: '45'),
    SuraModel(arName: "يس", enName: "Ya-Sin", ayaNumber: '83'),
    SuraModel(arName: "الصافات", enName: "As-Saffat", ayaNumber: '182'),
    SuraModel(arName: "ص", enName: "Sad", ayaNumber: '88'),
    SuraModel(arName: "الزمر", enName: "Az-Zumar", ayaNumber: '75'),
    SuraModel(arName: "غافر", enName: "Ghafir", ayaNumber: '85'),
    SuraModel(arName: "فصّلت", enName: "Fussilat", ayaNumber: '54'),
    SuraModel(arName: "الشورى", enName: "Ash-Shura", ayaNumber: '53'),
    SuraModel(arName: "الزخرف", enName: "Az-Zukhruf", ayaNumber: '89'),
    SuraModel(arName: "الدّخان", enName: "Ad-Dukhan", ayaNumber: '59'),
    SuraModel(arName: "الجاثية", enName: "Al-Jathiya", ayaNumber: '37'),
    SuraModel(arName: "الأحقاف", enName: "Al-Ahqaf", ayaNumber: '35'),
    SuraModel(arName: "محمد", enName: "Muhammad", ayaNumber: '38'),
    SuraModel(arName: "الفتح", enName: "Al-Fath", ayaNumber: '29'),
    SuraModel(arName: "الحجرات", enName: "Al-Hujurat", ayaNumber: '18'),
    SuraModel(arName: "ق", enName: "Qaf", ayaNumber: '45'),
    SuraModel(arName: "الذاريات", enName: "Adh-Dhariyat", ayaNumber: '60'),
    SuraModel(arName: "الطور", enName: "At-Tur", ayaNumber: '49'),
    SuraModel(arName: "النجم", enName: "An-Najm", ayaNumber: '62'),
    SuraModel(arName: "القمر", enName: "Al-Qamar", ayaNumber: '55'),
    SuraModel(arName: "الرحمن", enName: "Ar-Rahman", ayaNumber: '78'),
    SuraModel(arName: "الواقعة", enName: "Al-Waqi'a", ayaNumber: '96'),
    SuraModel(arName: "الحديد", enName: "Al-Hadid", ayaNumber: '29'),
    SuraModel(arName: "المجادلة", enName: "Al-Mujadila", ayaNumber: '22'),
    SuraModel(arName: "الحشر", enName: "Al-Hashr", ayaNumber: '24'),
    SuraModel(arName: "الممتحنة", enName: "Al-Mumtahina", ayaNumber: '13'),
    SuraModel(arName: "الصف", enName: "As-Saff", ayaNumber: '14'),
    SuraModel(arName: "الجمعة", enName: "Al-Jumu'a", ayaNumber: '11'),
    SuraModel(arName: "المنافقون", enName: "Al-Munafiqun", ayaNumber: '11'),
    SuraModel(arName: "التغابن", enName: "At-Taghabun", ayaNumber: '18'),
    SuraModel(arName: "الطلاق", enName: "At-Talaq", ayaNumber: '12'),
    SuraModel(arName: "التحريم", enName: "At-Tahrim", ayaNumber: '12'),
    SuraModel(arName: "الملك", enName: "Al-Mulk", ayaNumber: '30'),
    SuraModel(arName: "القلم", enName: "Al-Qalam", ayaNumber: '52'),
    SuraModel(arName: "الحاقة", enName: "Al-Haqqah", ayaNumber: '52'),
    SuraModel(arName: "المعارج", enName: "Al-Ma'arij", ayaNumber: '44'),
    SuraModel(arName: "نوح", enName: "Nuh", ayaNumber: '28'),
    SuraModel(arName: "الجن", enName: "Al-Jinn", ayaNumber: '28'),
    SuraModel(arName: "المزّمّل", enName: "Al-Muzzammil", ayaNumber: '20'),
    SuraModel(arName: "المدّثر", enName: "Al-Muddathir", ayaNumber: '56'),
    SuraModel(arName: "القيامة", enName: "Al-Qiyamah", ayaNumber: '40'),
    SuraModel(arName: "الإنسان", enName: "Al-Insan", ayaNumber: '31'),
    SuraModel(arName: "المرسلات", enName: "Al-Mursalat", ayaNumber: '50'),
    SuraModel(arName: "النبأ", enName: "An-Naba'", ayaNumber: '40'),
    SuraModel(arName: "النازعات", enName: "An-Nazi'at", ayaNumber: '46'),
    SuraModel(arName: "عبس", enName: "Abasa", ayaNumber: '42'),
    SuraModel(arName: "التكوير", enName: "At-Takwir", ayaNumber: '29'),
    SuraModel(arName: "الإنفطار", enName: "Al-Infitar", ayaNumber: '19'),
    SuraModel(arName: "المطفّفين", enName: "Al-Mutaffifin", ayaNumber: '36'),
    SuraModel(arName: "الإنشقاق", enName: "Al-Inshiqaq", ayaNumber: '25'),
    SuraModel(arName: "البروج", enName: "Al-Buruj", ayaNumber: '22'),
    SuraModel(arName: "الطارق", enName: "At-Tariq", ayaNumber: '17'),
    SuraModel(arName: "الأعلى", enName: "Al-A'la", ayaNumber: '19'),
    SuraModel(arName: "الغاشية", enName: "Al-Ghashiyah", ayaNumber: '26'),
    SuraModel(arName: "الفجر", enName: "Al-Fajr", ayaNumber: '30'),
    SuraModel(arName: "البلد", enName: "Al-Balad", ayaNumber: '20'),
    SuraModel(arName: "الشمس", enName: "Ash-Shams", ayaNumber: '15'),
    SuraModel(arName: "الليل", enName: "Al-Lail", ayaNumber: '21'),
    SuraModel(arName: "الضحى", enName: "Ad-Duha", ayaNumber: '11'),
    SuraModel(arName: "الشرح", enName: "Ash-Sharh", ayaNumber: '8'),
    SuraModel(arName: "التين", enName: "At-Tin", ayaNumber: '8'),
    SuraModel(arName: "العلق", enName: "Al-Alaq", ayaNumber: '19'),
    SuraModel(arName: "القدر", enName: "Al-Qadr", ayaNumber: '5'),
    SuraModel(arName: "البينة", enName: "Al-Bayyina", ayaNumber: '8'),
    SuraModel(arName: "الزلزلة", enName: "Az-Zalzalah", ayaNumber: '8'),
    SuraModel(arName: "العاديات", enName: "Al-Adiyat", ayaNumber: '11'),
    SuraModel(arName: "القارعة", enName: "Al-Qari'a", ayaNumber: '11'),
    SuraModel(arName: "التكاثر", enName: "At-Takathur", ayaNumber: '8'),
    SuraModel(arName: "العصر", enName: "Al-Asr", ayaNumber: '3'),
    SuraModel(arName: "الهمزة", enName: "Al-Humazah", ayaNumber: '9'),
    SuraModel(arName: "الفيل", enName: "Al-Fil", ayaNumber: '5'),
    SuraModel(arName: "قريش", enName: "Quraysh", ayaNumber: '4'),
    SuraModel(arName: "الماعون", enName: "Al-Ma'un", ayaNumber: '7'),
    SuraModel(arName: "الكوثر", enName: "Al-Kawthar", ayaNumber: '3'),
    SuraModel(arName: "الكافرون", enName: "Al-Kafirun", ayaNumber: '6'),
    SuraModel(arName: "النصر", enName: "An-Nasr", ayaNumber: '3'),
    SuraModel(arName: "المسد", enName: "Al-Masad", ayaNumber: '5'),
    SuraModel(arName: "الإخلاص", enName: "Al-Ikhlas", ayaNumber: '4'),
    SuraModel(arName: "الفلق", enName: "Al-Falaq", ayaNumber: '5'),
    SuraModel(arName: "الناس", enName: "An-Nas", ayaNumber: '6'),
  ];
}
